# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            '> Kyle Berthelette'
# tagline:          'A Jekyll theme'
description:      'Linux User & Dev;<br/>
                  Storage enthusiast;<br/>
                  PC Gamer;'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kyle Berthelette'
  # url:            https://twitter.com/mdo

social:
  # facebook:       https://www.facebook.com/kberthelett
  linkedin:       https://www.linkedin.com/in/kyle-berthelette-1589aa34
  github:         https://github.com/kberthelett

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
